massdriver-cloud/mass

cmd/bundle.go
internal/bundle/prompt.go

To prevent accidently public publishing and to remove the friction of users having to pick, bundle access will be set as private by default and will require and override flag to set to public.

Bundle Access Private By Default

---

internal/commands/image/push.go
internal/commands/image/push_test.go

If `mass image push` is invoked with an image tag other than "latest", push "latest" in addition to whichever tag was specified.

image push: Always push "latest" tag

---

internal/commands/image/docker_client.go

regexp.MustCompile should be a package level var, this will allow for the program to panic on first startup vs in the middle of running. It can also be a performance improvement if the regexp is used in a hot code path as the expression would be compiled every time that piece of code is hit.

Move dockerURI regexp to package var

---

.github/workflows/lint.yaml
.github/workflows/pre-commit.yaml
.github/workflows/release.yaml
.github/workflows/test.yaml
.gitignore
.goreleaser.yaml

Example of how the releases will look from my branch: https://github.com/dramich/mass/releases/tag/1.5.0
Note that the changlog is huge because I have no previous tags in my repo to diff.

Bump github-action dependencies and move to go-releaser

---

internal/commands/image/push.go

We aren't building the image with the `latest` tag, and therefore docker can't find the `latest` image to push.
I'm not sure how this worked in the first place or what broke it, but this should unblock us.
Mid-term, the correct fix is to expand PushImageInput Tag to be a []string, and add the tag from the tag flag to it, as well as `latest` if the flag tag is not `latest`. This way the tags get passed to both `BuildImage` and `PushImage`.

Remove pushing `latest` image

---

Makefile
pkg/api/main.go
pkg/api/schema.graphql
pkg/api/zz_generated.go
scripts/graphql-gen.sh

Use a docker container to run the schema generation so
mix and other tools are not required locally. This relies on the
dev image in massdriver and will build it if not available.
Update the go generate command to specify a version which allows the
gen to run without having to modify the go.mod file

Changes to graphql generation 

---

cmd/server.go
pkg/server/server.go

This allows the UI to hit the endpoint like `http://127.0.0.1:8080/schema-ui.json` and pickup any of the json schema files (or any other file in the massdriver bundle dir)
`mass server -p 8080 -d massdriver`

Update server command to serve from a specified dir

---

cmd/server.go
pkg/proxy/proxy.go
pkg/server/server.go

This allows the UI to use the proxy to request resources from massdriver and avoid CORS issues.
Use like `curl http://127.0.0.1:8080/proxy/any-endpoint-you-want` which will translate to `https://api.massdriver.cloud/any-endpoint-you-want`

Add proxy for massdriver api

---

go.mod
go.sum
pkg/bundle/bundle.go
pkg/commands/build_bundle_test.go
pkg/commands/generate_new_bundle_test.go
pkg/files/files.go

This module is supported and also gives access to easy yaml > json conversion and back which will be needed in the future
This change unblocks the UI as well, when moving the yaml parsing I used the wrong version which broke the bundle yaml unmarshal 
For more context, go-yaml is unmaintained at this point, and k8s is pushing to fork it since it's pretty important https://github.com/kubernetes-sigs/yaml/pull/76

Swap yaml library to sigs.k8s.io/yaml

---

.gitignore

This is the default dir when running `mass bundle new` so add it to help people testing

Add massdriver dir to gitignore

---

cmd/application.go
cmd/artifact.go
cmd/bundle.go
cmd/image.go
cmd/infrastructure.go
cmd/preview.go
cmd/root.go
cmd/schema.go
cmd/version.go
pkg/version/version.go
pkg/version/version_test.go

Remove init functions and vars
Move instantiaion into function calls
This allows control over the order in which things get instantiated and the ability to process args/envs before inits are called

Refactor to use constructor pattern

---

.github/workflows/test.yaml

The action will run `mass docs` and fail if it finds a difference.

Add generation validation to github action

---

pkg/commands/preview_environment/initialize/main.go

Currently the help for next and back don't show up unless a user pushes `?`, this change always shows the keyboard commands now.

Always show help for preview init

---

pkg/container/container.go

This timeout causes the log read to stop and kills the websocket. It was added as safety for local testing but shouldn't be needed anymore.

Drop container log timeout

---

pkg/config/config.go

Adds a helpful message if the envvars are set but empty 
`Error: MASSDRIVER_API_KEY environment variable exists but has no value, please set a value to continue`

Add a check for blank envvars

---

cmd/bundle.go
pkg/terraform/generate_files.go

Add an assertion check to stop the panic if the field is missing
Add a nice error message to help people find the issue `Error: connections block is missing 'properties' entry`
Default both connections and artifacts to have empty props fields if they don't exist

Assertion check for properties

---

pkg/commands/build_bundle.go

Allow `helm` has a valid provisioner in bundle steps.

Add support for helm provisioner

---

cmd/image.go
docs/generated/mass_image_push.md
docs/helpdocs/image/push.md
pkg/commands/image/docker_client.go
pkg/commands/image/image.go
pkg/commands/image/push.go
pkg/commands/image/push_test.go

The default behavior is kept if the flag is not used so images will continue to be built.

Add flag to image push to skip build

---

.goreleaser.yaml

Reverts massdriver-cloud/mass#118
There are multiple path related issues that need to be addressed before we can have a windows release

Revert "Add windows build"

---

.devcontainer/Dockerfile
.github/workflows/lint.yaml
.github/workflows/pre-commit.yaml
.github/workflows/release.yaml
.github/workflows/test.yaml
go.mod

This is technically waiting on the devcontainer image to be released but everything else works.

Bump go to 1.22

---

cmd/server.go
docs/generated/mass_server.md
go.mod
go.sum
pkg/server/server.go

If the flag `--browser` is added, then the cli will attempt to open the bundle UI in a browser

Add browser flag when launching server 

---

pkg/commands/publish/main.go
pkg/jsonschema/dereference.go

* We emit an early "bundle published" message
* We do support fragments, we just don't do anything _to_ them

Removing two misleading log msgs.

---

cmd/bundle.go

Current issue and why it needs to be fixed:
```
❯ ../mass/bin/mass-linux-amd64 bundle new
2024/06/24 10:43:20 INFO Refreshing templates path=/home/michael/.massdriver
2024/06/24 10:43:20 INFO Templates are current, skipping download
2024/06/24 10:43:20 <nil>
```
Test results:
```
❯ ../mass/bin/mass-linux-amd64 bundle new
2024/06/24 11:02:32 INFO Refreshing templates path=/home/michael/.massdriver
2024/06/24 11:02:32 INFO Templates are current, skipping download
2024/06/24 11:02:32 required environment variable not set: OrgID: missing required value: MASSDRIVER_ORG_ID
```
and for API key, after setting ORG_ID
```
❯ ../mass/bin/mass-linux-amd64 bundle new
2024/06/24 11:02:50 INFO Refreshing templates path=/home/michael/.massdriver
2024/06/24 11:02:51 INFO Templates are current, skipping …
```

Fixing handling of bundle new error

---

pkg/config/config.go

There are certain API functions (specifically around state) that **ONLY** support ORG_ID being the org slug. Adding this warning to let people know they should update.
Going to wait to merge this until the org slug is easier to fetch in the app, and docs are updated to reflect new process.

Add warning if MASSDRIVER_ORG_ID is a UUID
